<a href="https://colab.research.google.com/github/Mai-Thanh-Thuan-15-4-2/Machine_Learning_23/blob/main/Lab_6_20130127_MaiThanhThuan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# This lab is to deal with classification task using **Random Forests** and **Na√Øve Bayes** algorithms with/without **Feature Selection**. 

*   **Deadline: 23:59, 25/03/2023**

# Import libraries

In [36]:
# code
from sklearn.svm import SVC
from sklearn import datasets
import pandas as pd
from prettytable import PrettyTable
from sklearn.datasets import load_iris
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif 
from numpy import set_printoptions

#Task 1. 
Task 1. Compare the performance of selected classification algorithms including **Random forest**, **NaiveBayes**, and **SVM** with **mnist** dataset based on **accuracy, precision, recall, f1** measures according to **without using selection feature** and **using selection feature**.

In [ ]:
# code
minist = datasets.load_digits()
digits = load_digits()

X = digits.data
y = digits.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets
clf.fit(X_train,y_train)
y_pred_1 = clf.predict(X_test)

In [ ]:
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
# SVM-rbf
svm = SVC(kernel='rbf', gamma=0.05, C=10, random_state=42)
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)

In [ ]:
# RandomForestClassifier
R1 = round(accuracy_score(y_test, y_pred_1), 3)
R2 = round(precision_score(y_test, y_pred_1, average="weighted"), 3)
R3 = round(recall_score(y_test, y_pred_1, average="weighted"), 3)
R4 = round(f1_score(y_test, y_pred_1, average="weighted"), 3)

In [ ]:
# Naive bayes
N1 = round(accuracy_score(y_test, y_pred),3)
N2 = round(precision_score(y_test, y_pred, average="weighted"), 3)
N3 = round(recall_score(y_test, y_pred, average="weighted"), 3)
N4 = round(f1_score(y_test, y_pred, average="weighted"), 3)

In [ ]:
# SVM
S1 = round(accuracy_score(y_test, y_pred_svm),3)
S2 = round(precision_score(y_test, y_pred_svm, average="weighted"), 3)
S3 = round(precision_score(y_test, y_pred_svm, average="weighted"), 3)
S4 = round(f1_score(y_test, y_pred_svm, average="weighted"), 3)

/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.9/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [ ]:
t = PrettyTable(['Algorithms','Accuracy', 'Precision', 'Recall', 'F1'])
t.add_row(['Random', R1, R2, R3, R4])
t.add_row(['Naive', N1, N2, N3, N4])
t.add_row(['SVM', S1, S2, S3, S4])
print(t)

+------------+----------+-----------+--------+-------+
| Algorithms | Accuracy | Precision | Recall |   F1  |
+------------+----------+-----------+--------+-------+
|   Random   |  0.969   |    0.97   | 0.969  |  0.97 |
|   Naive    |  0.847   |   0.875   | 0.847  | 0.849 |
|    SVM     |  0.078   |   0.006   | 0.006  | 0.011 |
+------------+----------+-----------+--------+-------+

#Task 2. 
For given bank dataset (bank.csv) having the following attributes :
1.	**age** (numeric)
2.	**job** : type of job (categorical: 'admin.','blue-collar','entrepreneur','housemaid','management','retired','self-employed','services','student','technician','unemployed','unknown')
3.	**marital** : marital status (categorical: 'divorced','married','single','unknown'; note: 'divorced' means divorced or widowed)
4.	**education** (categorical: 'basic.4y','basic.6y','basic.9y','high.school','illiterate','professional.course','university.degree','unknown')
5.	**default**: has credit in default? (categorical: 'no','yes','unknown')
6.	**housing**: has housing loan? (categorical: 'no','yes','unknown')
7.	**loan**: has personal loan? (categorical: 'no','yes','unknown')
8.	**contact**: contact communication type (categorical: 'cellular','telephone')
9.	**month**: last contact month of year (categorical: 'jan', 'feb', 'mar', ..., 'nov', 'dec')
10.	**day_of_week**: last contact day of the week (categorical: 'mon','tue','wed','thu','fri')
11.	**duration**: last contact duration, in seconds (numeric). Important note: this attribute highly affects the output target (e.g., if duration=0 then y='no'). Yet, the duration is not known before a call is performed. Also, after the end of the call y is obviously known. Thus, this input should only be included for benchmark purposes and should be discarded if the intention is to have a realistic predictive model.
12.	**campaign**: number of contacts performed during this campaign and for this client (numeric, includes last contact)
13.	**pdays**: number of days that passed by after the client was last contacted from a previous campaign (numeric; 999 means client was not previously contacted)
14.	**previous**: number of contacts performed before this campaign and for this client (numeric)
15.	**poutcome**: outcome of the previous marketing campaign (categorical: 'failure','nonexistent','success')
Output variable (desired target):
16.	**y**. has the client subscribed a term deposit? (binary: 'yes','no')

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')
%cd '/content/gdrive/MyDrive/20130127_MaiThanhThuan'

Mounted at /content/gdrive
/content/gdrive/MyDrive/20130127_MaiThanhThuan

In [6]:
dataset = pd.read_csv('/content/gdrive/MyDrive/20130127_MaiThanhThuan/bank.csv')
dataset

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,59,admin.,married,secondary,no,2343,yes,no,unknown,5,may,1042,1,-1,0,unknown,yes
1,56,admin.,married,secondary,no,45,no,no,unknown,5,may,1467,1,-1,0,unknown,yes
2,41,technician,married,secondary,no,1270,yes,no,unknown,5,may,1389,1,-1,0,unknown,yes
3,55,services,married,secondary,no,2476,yes,no,unknown,5,may,579,1,-1,0,unknown,yes
4,54,admin.,married,tertiary,no,184,no,no,unknown,5,may,673,2,-1,0,unknown,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33,blue-collar,single,primary,no,1,yes,no,cellular,20,apr,257,1,-1,0,unknown,no
11158,39,services,married,secondary,no,733,no,no,unknown,16,jun,83,4,-1,0,unknown,no
11159,32,technician,single,secondary,no,29,no,no,cellular,19,aug,156,2,-1,0,unknown,no
11160,43,technician,married,secondary,no,0,no,yes,cellular,8,may,9,2,172,5,failure,no
11161,34,technician,married,secondary,no,0,no,no,cellular,9,jul,628,1,-1,0,unknown,no

#3.1. Apply StandardScaler() function to columns that contains numerical data ('age', 'balance', 'day', 'campaign', 'pdays', 'previous')

In [8]:


names = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
array_data = dataset[names]


scaler = StandardScaler()
scaler.fit(array_data)


scaled_data = pd.DataFrame(scaler.transform(array_data), columns=names)


dataset[names] = scaled_data


dataset.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,1.491505,admin.,married,secondary,no,0.252525,yes,no,unknown,-1.265746,may,1042,-0.554168,-0.481184,-0.36326,unknown,yes
1,1.239676,admin.,married,secondary,no,-0.459974,no,no,unknown,-1.265746,may,1467,-0.554168,-0.481184,-0.36326,unknown,yes
2,-0.019470,technician,married,secondary,no,-0.080160,yes,no,unknown,-1.265746,may,1389,-0.554168,-0.481184,-0.36326,unknown,yes
3,1.155733,services,married,secondary,no,0.293762,yes,no,unknown,-1.265746,may,579,-0.554168,-0.481184,-0.36326,unknown,yes
4,1.071790,admin.,married,tertiary,no,-0.416876,no,no,unknown,-1.265746,may,673,-0.186785,-0.481184,-0.36326,unknown,yes

#3.2. Apply Encode Categorical Value (OneHotEncoder) to transfrom categorical data to numerical data ('job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome')

In [9]:
#code
onehot = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

encoder = OneHotEncoder()

encoded_cols = encoder.fit_transform(dataset[onehot]).toarray()
encoded_df = pd.DataFrame(encoded_cols, columns=encoder.get_feature_names_out(onehot))

data_concat = pd.concat([dataset.drop(onehot, axis=1), encoded_df], axis=1)

print(data_concat)
pd.get_dummies(data_concat,columns=['age', 'balance', 'day', 'campaign', 'pdays', 'previous'],drop_first=True)

            age   balance       day  duration  campaign     pdays  previous  \
0      1.491505  0.252525 -1.265746      1042 -0.554168 -0.481184 -0.363260
1      1.239676 -0.459974 -1.265746      1467 -0.554168 -0.481184 -0.363260
2     -0.019470 -0.080160 -1.265746      1389 -0.554168 -0.481184 -0.363260
3      1.155733  0.293762 -1.265746       579 -0.554168 -0.481184 -0.363260
4      1.071790 -0.416876 -1.265746       673 -0.186785 -0.481184 -0.363260
...         ...       ...       ...       ...       ...       ...       ...
11157 -0.691015 -0.473616  0.515650       257 -0.554168 -0.481184 -0.363260
11158 -0.187357 -0.246658  0.040612        83  0.547981 -0.481184 -0.363260
11159 -0.774958 -0.464934  0.396891       156 -0.186785 -0.481184 -0.363260
11160  0.148416 -0.473926 -0.909466         9 -0.186785  1.109571  1.818332
11161 -0.607072 -0.473926 -0.790707       628 -0.554168 -0.481184 -0.363260

      deposit  job_admin.  job_blue-collar  ...  month_jun  month_mar  \
0         yes         1.0              0.0  ...        0.0        0.0
1         yes         1.0              0.0  ...        0.0        0.0
2         yes         0.0              0.0  ...        0.0        0.0
3         yes         0.0              0.0  ...        0.0        0.0
4         yes         1.0              0.0  ...        0.0        0.0
...       ...         ...              ...  ...        ...        ...
11157      no         0.0              1.0  ...        0.0        0.0
11158      no         0.0              0.0  ...        1.0        0.0
11159      no         0.0              0.0  ...        0.0        0.0
11160      no         0.0              0.0  ...        0.0        0.0
11161      no         0.0              0.0  ...        0.0        0.0

       month_may  month_nov  month_oct  month_sep  poutcome_failure  \
0            1.0        0.0        0.0        0.0               0.0
1            1.0        0.0        0.0        0.0               0.0
2            1.0        0.0        0.0        0.0               0.0
3            1.0        0.0        0.0        0.0               0.0
4            1.0        0.0        0.0        0.0               0.0
...          ...        ...        ...        ...               ...
11157        0.0        0.0        0.0        0.0               0.0
11158        0.0        0.0        0.0        0.0               0.0
11159        0.0        0.0        0.0        0.0               0.0
11160        1.0        0.0        0.0        0.0               1.0
11161        0.0        0.0        0.0        0.0               0.0

       poutcome_other  poutcome_success  poutcome_unknown
0                 0.0               0.0               1.0
1                 0.0               0.0               1.0
2                 0.0               0.0               1.0
3                 0.0               0.0               1.0
4                 0.0               0.0               1.0
...               ...               ...               ...
11157             0.0               0.0               1.0
11158             0.0               0.0               1.0
11159             0.0               0.0               1.0
11160             0.0               0.0               0.0
11161             0.0               0.0               1.0

[11162 rows x 52 columns]

,duration,deposit,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,...,previous_10.98101714203471,previous_11.417335487676663,previous_11.853653833318614,previous_12.289972178960566,previous_12.726290524602518,previous_15.78051894409618,previous_17.089473981022035,previous_17.52579232666399,previous_23.634249165651312,previous_24.943204202577167
0,1042,yes,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1467,yes,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,1389,yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,579,yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
4,673,yes,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,257,no,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
11158,83,no,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
11159,156,no,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
11160,9,no,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
11161,628,no,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

#3.3. Apply **Decision tree, Random forest, kNN, Na√ØveBayes** to preproceed dataset in the previous steps. Then compare the obtained results using **accuracy, precision, recall, f1** measures.

In [32]:
#code
X_train, X_test, y_train, y_test = train_test_split(data_concat.iloc[:,0:7], data_concat.iloc[:,-1], test_size=0.3, random_state=42)

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dtp = dt.predict(X_test)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_predicted = rf.predict(X_test)

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
knnp = knn.predict(X_test)

nb = GaussianNB()
nb.fit(X_train, y_train)
nbp = nb.predict(X_test)

dt_accuracy = accuracy_score(y_test, dtp)
dt_precision = precision_score(y_test, dtp)
dt_recall = recall_score(y_test, dtp)
dt_f1 = f1_score(y_test, dtp)

rf_accuracy = accuracy_score(y_test, rf_predicted)
rf_precision = precision_score(y_test, rf_predicted)
rf_recall = recall_score(y_test, rf_predicted)
rf_f1 = f1_score(y_test, rf_predicted)

knn_accuracy = accuracy_score(y_test, knnp)
knn_precision = precision_score(y_test, knnp)
knn_recall = recall_score(y_test, knnp)
knn_f1 = f1_score(y_test,knnp)

nb_accuracy = accuracy_score(y_test, nbp)
nb_precision = precision_score(y_test, nbp)
nb_recall = recall_score(y_test, nbp)
nb_f1 = f1_score(y_test, nbp)

# Print the results
print("Results for Decision Tree : ")
print("Accuracy -", dt_accuracy)
print("Precision -", dt_precision)
print("Recall -", dt_recall)
print("F1 Score -", dt_f1)
print()
print("Results for Random Forest : ")
print("Accuracy -", rf_accuracy)
print("Precision -", rf_precision)
print("Recall -", rf_recall)
print("F1 Score -", rf_f1)
print()
print("Results for kNN : ")
print("Accuracy -", knn_accuracy)
print("Precision -", knn_precision)
print("Recall -", knn_recall)
print("F1 Score -", knn_f1)
print()
print("Results for Naive Bayes : ")
print("Accuracy -", nb_accuracy)
print("Precision -", nb_precision)
print("Recall -", nb_recall)
print("F1 Score -", nb_f1)

Results for Decision Tree :
Accuracy - 0.9997014034040012
Precision - 1.0
Recall - 0.999593165174939
F1 Score - 0.999796541200407

Results for Random Forest :
Accuracy - 0.9997014034040012
Precision - 1.0
Recall - 0.999593165174939
F1 Score - 0.999796541200407

Results for kNN :
Accuracy - 0.9035532994923858
Precision - 0.8849621348719798
Recall - 0.9983726606997559
F1 Score - 0.9382527241445232

Results for Naive Bayes :
Accuracy - 0.9982084204240071
Precision - 1.0
Recall - 0.9975589910496339
F1 Score - 0.9987780040733197

#3.4. Using selection feature to above dataset, then compare the classification results with those in Task 2.3.

In [39]:
X = data_concat.iloc[:,0:7]
y =  data_concat.iloc[:,-1]

In [40]:
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, y)
set_printoptions(precision=3)
features = fit.transform(X)

In [41]:

model = LogisticRegression(solver='lbfgs')
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X, y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Num Features: 3
Selected Features: [False False False False  True  True  True]
Feature Ranking: [2 3 4 5 1 1 1]

In [42]:
pca = PCA(n_components=3)
fit = pca.fit(X)

print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [1.000e+00 1.294e-05 9.240e-06]
[[ 5.452e-07  6.464e-05 -5.333e-05  1.000e+00 -1.197e-04 -7.891e-05
  -7.697e-05]
 [ 4.341e-02  6.857e-02 -2.205e-01  5.893e-05 -2.397e-01  6.731e-01
   6.590e-01]
 [ 6.625e-01  6.705e-01  2.675e-01 -2.773e-06  1.929e-01 -5.503e-03
   5.189e-02]]

In [43]:
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, y)
print(model.feature_importances_)

[0.003 0.002 0.004 0.004 0.007 0.694 0.286]

#Task 4. 
For a given dataset in the Lab #5 (**credit card dataset**), perform feature selection and thencompare the performance of selected classification algorithms (Decision Tree, kNN, Logistic Regression, SVM, Random Forest and NaiveBayes) based on accuracy, precision, recall, f1 measures.

In [47]:
# code
card_data = pd.read_csv('creditcard.csv')
array = card_data.values
X = array[:,0:8]
Y = array[:,8]
set_printoptions(precision=3)

features = fit.transform(X)

print(features[0:5,:])
model = LogisticRegression(solver='lbfgs')
rfe = RFE(estimator=model, n_features_to_select=3)
fit = rfe.fit(X, Y)
pca = PCA(n_components=3)
fit = pca.fit(X)
model = ExtraTreesClassifier(n_estimators=10)
model.fit(X, Y)
clf=RandomForestClassifier(n_estimators=100)

feature_imp = pd.Series(clf.feature_importances_,index=dataset.feature_names).sort_values(ascending=False)
feature_imp
clf.fit(X_train,y_train)
df = pd.DataFrame(dataset['data'], columns =dataset.feature_names)
df['species'] = dataset['target']
X1=df.drop("Class",axis=1)
y1=df['class']                                       

X_train1, X_test1, y_train1, y_test1 = train_test_split(X1, y1, test_size=0.3, random_state=1)
tree = tree.DecisionTreeClassifier()
tree.fit(X_train1, y_train1)

knn = KNeighborsClassifier()
knn.fit(X_train1, y_train1)

lr = LogisticRegression()
lr.fit(X_train1, y_train1)

svm = svm.SVC()
svm.fit(X_train1, y_train1)

rf = RandomForestClassifier()
rf.fit(X_train1, y_train1)

nb = GaussianNB()
nb.fit(X_train1, y_train1)

dt_pred = tree.predict(X_test1)
dt_acc = accuracy_score(y_test1, dt_pred)
dt_prec = precision_score(y_test1, dt_pred, average='macro')
dt_recall = recall_score(y_test1, dt_pred, average='macro')
dt_f1 = f1_score(y_test1, dt_pred, average='macro')

     

knn_pred = knn.predict(X_test1)
knn_acc = accuracy_score(y_test1, knn_pred)
knn_prec = precision_score(y_test1, knn_pred, average='macro')
knn_recall = recall_score(y_test1, knn_pred, average='macro')
knn_f1 = f1_score(y_test1, knn_pred, average='macro')
     

lr_pred =lr.predict(X_test1)
lr_acc = accuracy_score(y_test1, lr_pred)
lr_prec = precision_score(y_test1, lr_pred, average='macro')
lr_recall = recall_score(y_test1, lr_pred, average='macro')
lr_f1 = f1_score(y_test1, lr_pred, average='macro')
     

svm_pred = svm.predict(X_test1)
svm_acc = accuracy_score(y_test1, svm_pred)
svm_prec = precision_score(y_test1, svm_pred, average='macro')
svm_recall = recall_score(y_test1, svm_pred, average='macro')
svm_f1 = f1_score(y_test1, svm_pred, average='macro')
     

rf_pred = rf.predict(X_test1)
rf_acc = accuracy_score(y_test1, rf_pred)
rf_prec = precision_score(y_test1, rf_pred, average='macro')
rf_recall = recall_score(y_test1, rf_pred, average='macro')
rf_f1 = f1_score(y_test1, rf_pred, average='macro')
     


nb_pred = nb.predict(X_test1)
nb_acc = accuracy_score(y_test1, nb_pred)
nb_prec = precision_score(y_test1, nb_pred, average='macro')
nb_recall = recall_score(y_test1, nb_pred, average='macro')
nb_f1 = f1_score(y_test1, nb_pred, average='macro')

/usr/local/lib/python3.9/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but PCA was fitted with feature names
  warnings.warn(

ValueError: ignored

#Finally,
Save a copy in your Github. Remember renaming the notebook.